apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: production
    owner: mouhamed
    webserver: nginx
    country: morocco
spec:
  containers:
    - name: nginx
      image: nginx:1.21.4
      ports:
        - containerPort: 80